/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LocationHistory } from "./LocationHistory";
import { LocationHistoryCountArgs } from "./LocationHistoryCountArgs";
import { LocationHistoryFindManyArgs } from "./LocationHistoryFindManyArgs";
import { LocationHistoryFindUniqueArgs } from "./LocationHistoryFindUniqueArgs";
import { DeleteLocationHistoryArgs } from "./DeleteLocationHistoryArgs";
import { LocationHistoryService } from "../locationHistory.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => LocationHistory)
export class LocationHistoryResolverBase {
  constructor(
    protected readonly service: LocationHistoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "LocationHistory",
    action: "read",
    possession: "any",
  })
  async _locationHistoriesMeta(
    @graphql.Args() args: LocationHistoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [LocationHistory])
  @nestAccessControl.UseRoles({
    resource: "LocationHistory",
    action: "read",
    possession: "any",
  })
  async locationHistories(
    @graphql.Args() args: LocationHistoryFindManyArgs
  ): Promise<LocationHistory[]> {
    return this.service.locationHistories(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => LocationHistory, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "LocationHistory",
    action: "read",
    possession: "own",
  })
  async locationHistory(
    @graphql.Args() args: LocationHistoryFindUniqueArgs
  ): Promise<LocationHistory | null> {
    const result = await this.service.locationHistory(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => LocationHistory)
  @nestAccessControl.UseRoles({
    resource: "LocationHistory",
    action: "delete",
    possession: "any",
  })
  async deleteLocationHistory(
    @graphql.Args() args: DeleteLocationHistoryArgs
  ): Promise<LocationHistory | null> {
    try {
      return await this.service.deleteLocationHistory(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
