/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UnlockAttempt } from "./UnlockAttempt";
import { UnlockAttemptCountArgs } from "./UnlockAttemptCountArgs";
import { UnlockAttemptFindManyArgs } from "./UnlockAttemptFindManyArgs";
import { UnlockAttemptFindUniqueArgs } from "./UnlockAttemptFindUniqueArgs";
import { DeleteUnlockAttemptArgs } from "./DeleteUnlockAttemptArgs";
import { UnlockAttemptService } from "../unlockAttempt.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UnlockAttempt)
export class UnlockAttemptResolverBase {
  constructor(
    protected readonly service: UnlockAttemptService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UnlockAttempt",
    action: "read",
    possession: "any",
  })
  async _unlockAttemptsMeta(
    @graphql.Args() args: UnlockAttemptCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UnlockAttempt])
  @nestAccessControl.UseRoles({
    resource: "UnlockAttempt",
    action: "read",
    possession: "any",
  })
  async unlockAttempts(
    @graphql.Args() args: UnlockAttemptFindManyArgs
  ): Promise<UnlockAttempt[]> {
    return this.service.unlockAttempts(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UnlockAttempt, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UnlockAttempt",
    action: "read",
    possession: "own",
  })
  async unlockAttempt(
    @graphql.Args() args: UnlockAttemptFindUniqueArgs
  ): Promise<UnlockAttempt | null> {
    const result = await this.service.unlockAttempt(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UnlockAttempt)
  @nestAccessControl.UseRoles({
    resource: "UnlockAttempt",
    action: "delete",
    possession: "any",
  })
  async deleteUnlockAttempt(
    @graphql.Args() args: DeleteUnlockAttemptArgs
  ): Promise<UnlockAttempt | null> {
    try {
      return await this.service.deleteUnlockAttempt(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
