/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UnlockAttemptService } from "../unlockAttempt.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UnlockAttemptCreateInput } from "./UnlockAttemptCreateInput";
import { UnlockAttempt } from "./UnlockAttempt";
import { UnlockAttemptFindManyArgs } from "./UnlockAttemptFindManyArgs";
import { UnlockAttemptWhereUniqueInput } from "./UnlockAttemptWhereUniqueInput";
import { UnlockAttemptUpdateInput } from "./UnlockAttemptUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UnlockAttemptControllerBase {
  constructor(
    protected readonly service: UnlockAttemptService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UnlockAttempt })
  @nestAccessControl.UseRoles({
    resource: "UnlockAttempt",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createUnlockAttempt(
    @common.Body() data: UnlockAttemptCreateInput
  ): Promise<UnlockAttempt> {
    return await this.service.createUnlockAttempt({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [UnlockAttempt] })
  @ApiNestedQuery(UnlockAttemptFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UnlockAttempt",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async unlockAttempts(
    @common.Req() request: Request
  ): Promise<UnlockAttempt[]> {
    const args = plainToClass(UnlockAttemptFindManyArgs, request.query);
    return this.service.unlockAttempts({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UnlockAttempt })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UnlockAttempt",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async unlockAttempt(
    @common.Param() params: UnlockAttemptWhereUniqueInput
  ): Promise<UnlockAttempt | null> {
    const result = await this.service.unlockAttempt({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UnlockAttempt })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UnlockAttempt",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateUnlockAttempt(
    @common.Param() params: UnlockAttemptWhereUniqueInput,
    @common.Body() data: UnlockAttemptUpdateInput
  ): Promise<UnlockAttempt | null> {
    try {
      return await this.service.updateUnlockAttempt({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UnlockAttempt })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UnlockAttempt",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUnlockAttempt(
    @common.Param() params: UnlockAttemptWhereUniqueInput
  ): Promise<UnlockAttempt | null> {
    try {
      return await this.service.deleteUnlockAttempt({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
